Fix readme
yiisoft/template pull request #15
Opened 2020-10-16 09:34 UTC by romkatsu

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | Fix readme

2020-10-16 10:13 UTC, roxblnfk approved these changes

2020-10-17 10:07 UTC, xepozz requested changes

2020-10-17 10:07 UTC, xepozz commented on README.md
> +composer require yiisoft/_____
```suggestion
composer req yiisoft/_____ --prefer-dist
```

2020-10-18 09:32 UTC, xepozz approved these changes

2020-10-18 22:22 UTC, merged

2020-10-18 22:22 UTC, samdark commented
Thanks!